# Generated by Django 5.0.1 on 2025-10-12 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('water', 'Water & Sanitation'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('environment', 'Environment'), ('poverty', 'Poverty Alleviation'), ('disaster', 'Disaster Relief'), ('human_rights', 'Human Rights'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('wallet_address', models.CharField(max_length=42, unique=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('donor_count', models.IntegerField(default=0)),
                ('image_emoji', models.CharField(default='🌍', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='organizations.organization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
